version: '3.8'
services:

  #Redis
  redis:
    image: redis:bullseye
    container_name: redis

  # Postgres Database
  db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    volumes: 
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    
  # Django Backend Application
  backend:
    build: .
    volumes:
      - .:/backend
    ports:
      - 8000:8000
    image: aaxl/tradecore
    container_name: backend_django
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  # Celery
  celery:
    restart: always
    build:
      context: .
    command: celery -A src.celery worker -l DEBUG
    volumes:
      - .:/backend
    container_name: celery
    depends_on:
      - db
      - redis
      - backend